version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: pitwall_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: pitwall_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pitwall_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pitwall_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pitwall_net

volumes:
  postgres_data:

networks:
  pitwall_net:
    driver: bridge
